// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::drivelDrive = NULL;
SpeedController* RobotMap::driverDrive = NULL;
RobotDrive* RobotMap::driveRobotDrive21 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	drivelDrive = new Victor(0);
	lw->AddActuator("Drive", "lDrive", (Victor*) drivelDrive);
	
	driverDrive = new Victor(1);
	lw->AddActuator("Drive", "rDrive", (Victor*) driverDrive);
	
	driveRobotDrive21 = new RobotDrive(drivelDrive, driverDrive);
	
	driveRobotDrive21->SetSafetyEnabled(true);
        driveRobotDrive21->SetExpiration(0.1);
        driveRobotDrive21->SetSensitivity(0.5);
        driveRobotDrive21->SetMaxOutput(1.0);
        


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
